### ISSUE TITLE
Support for latex style math-mode fencing using $ (inline) and $$ (display mode)

### ISSUE THREAD

**Issue by zhzhzoo** [linjer/jekyll-katex#1]

**Comment by stevecheckoway** [comment]
It clearly does not support `$…$` or `$$…$$`, but it would be nice. Having a switch to turn it on or off would be particularly great.

```
Dollar signs ($) are treated normally here.
{% katex on %}
Now every dollar renders math $x+y$.
…
{% katex off %}
Back to normal treatment.
```

**Comment by linjer** [comment]
This is a really great idea. I like this over having to open and close blocks everywhere. I think it would be fairly easy to implement. I'll give an implementation a try when I can.

**Comment by linjer** [comment]
@zhzhzoo @stevecheckoway I've opened PR #5 to address this. If you have the chance to give it a review I'd appreciate it. 

If I don't hear from either of you within the next few days, I'll go ahead and publish the changes and hopefully it improves your experience.

**Comment by stevecheckoway** [comment]
I actually ended up writing my own implementation a while back. I’ll dig up the details later but I’m about to take off. So no need to wait for me.

**Comment by linjer** [comment]
@stevecheckoway maybe more reason to wait for your input or a PR from your side. Hopefully you have some time to help.

**Comment by linjer** [comment]
This feature has been added in version 0.3.0
