### ISSUE TITLE
Line breaker not support

### ISSUE THREAD

**Issue by Fenzland** [linjer/jekyll-katex#12]
KaTeX support line breakers \\ and \newline.
But with jekyll-katex, \\ rise a error, and \newline is not work too.

**Comment by Fenzland** [comment]
maybe up the katex.min.js to date will hellp this

**Comment by linjer** [comment]
@Fenzland Thanks for the report. Can you try to manually set the `katex.min.js` version for your use case and let me know if that solves the problem?

If not, a little more information about how to produce the issue would be helpful.

**Comment by linjer** [comment]
@Fenzland I've bumped the katex version to `0.10.1` in the the gem version `0.4.1`. Please try it out.

I don't think I had enough understanding of the issue to reproduce the issue so I'll close this issue for now. Feel free to file a new issue if the upgrade does not help.
