### ISSUE TITLE
Incorrect path output for KaTeX js

### ISSUE THREAD

**Issue by ashmaroli** [linjer/jekyll-katex#13]
Currently the log output shows:
```
Katex Configuration: Found KaTeX js at: ~/lib/assets/js//katex.min.js
```
Notice the double slash `//` between the `:js_path` and the `:js_filename` values

**Comment by linjer** [comment]
Thanks for letting me know. Just to clarify, it sounds like this does not effectively break anything as far as you know? Is that correct?

**Comment by ashmaroli** [comment]
Correct. This doesn't break anything but still worth fixing.
But why would you consider this to be an enhancement? It looks like a bug-fix to me..

**Comment by linjer** [comment]
@ashmaroli I think we might just have different semantics for what each means. I would typically tag something a `bug` if causes unintended behavior, while `enhancement` is an improvement that may not be fixing unintended behavior.

I agree this is worth fixing as it may cause other issues unknown to us at this time or break things later.

I'm in the middle of a move to a new home. Will get to this around May. If you want to help fix this before then, feel free to open a PR.

**Comment by ashmaroli** [comment]
Yep. We have differing semantics for what an *enhancement* means. Sorry about that.
I can submit a PR. No probs.
