### ISSUE TITLE
Update to KaTeX 0.9.0?

### ISSUE THREAD

**Issue by jluttine** [linjer/jekyll-katex#2]
Hi, thanks for this package! There's a new KaTeX release. Would be great if this package used that.

**Comment by linjer** [comment]
I'll cut a new version soon. Thanks for bringing it to my attention.

**Comment by linjer** [comment]
I've cut a new release, version `0.1.4` to rubygems which has KaTeX `0.9.0` pre-packaged. I'll do some cleanup and add documentation for how people can override the packaged version.

**Comment by linjer** [comment]
I just pushed a version `0.2.0` which allows you to configure a few things, including the `katex.js` file to use if you want to use a different version than one packaged. Readme for this repo has more information.
