### ISSUE TITLE
Jekyll 4 support

### ISSUE THREAD

**Issue by boramalper** [linjer/jekyll-katex#27]
[Jekyll 4 is released recently](https://jekyllrb.com/news/2019/08/20/jekyll-4-0-0-released/) and jekyll-katex depends on Jekyll 3.0 thus won't work with the latest version.

**Comment by MahdiBaghbani** [comment]
I had actually tested jekyll-katex (a modified fork that has jekyll 4.0 as requirement) and everything went good. I think it's safe to update gem file to point at the new jekyll version.

**Comment by linjer** [comment]
@boramalper Thanks for raising this to my attention. Can you try and see if version `1.0.0` I just published now works?

**Comment by boramalper** [comment]
You're welcome! I am afraid I cannot help as I already opted for manually setting it up in my themes (and giving up on server-side rendering).

**Comment by MahdiBaghbani** [comment]
I've already played with it in my developing Jekyll theme, can confirm it worked for version 4 and rendered existing math expressions. but my math expressions are so simple and few (5 at all).

**Comment by linjer** [comment]
@boramalper Sorry I couldn't provide timely support. I have stopped maintaining a Jekyll site entirely so I am unfortunately no longer a user. I'll close out this issue for now as a result and if you or anyone else finds the problems persist, please let me know.

@MahdiBaghbani If I am understanding you correctly, you've tried playing around with the published `1.0.0` version and it seems to be working for the simple cases you have. Am I correct? Thank you so much for contributing.

**Comment by MahdiBaghbani** [comment]
yes, It worked for me.

**Comment by boramalper** [comment]
@linjer No worries at all! Thank you for your hard work. =)
